[package]
name = "jacoco2cobertura"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.53"
clap = { version = "3.1.0", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
quick-xml = { version = "0.22.0", features = ["serialize"] }
