[package]
name = "jacoco2cobertura"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
serde = { version = "1.0.163", features = ["derive"] }
quick-xml = { version = "0.28.2", features = ["serialize"] }