[package]
name = "jacoco2cobertura"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.60"
clap = { version = "3.2.16", features = ["derive"] }
serde = { version = "1.0.142", features = ["derive"] }
quick-xml = { version = "0.23.0", features = ["serialize"] }