[package]
name = "jacoco2cobertura"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.66"
clap = { version = "3.2.23", features = ["derive"] }
serde = { version = "1.0.147", features = ["derive"] }
quick-xml = { version = "0.26.0", features = ["serialize"] }