[package]
name = "jacoco2cobertura"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0.197", features = ["derive"] }
quick-xml = { version = "0.31.0", features = ["serialize"] }