[package]
name = "jacoco2cobertura"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
clap = { version = "4.5.4", features = ["derive"] }
serde = { version = "1.0.199", features = ["derive"] }
quick-xml = { version = "0.36.0", features = ["serialize"] }